version: "3.8"
services:
  openinterpreter:
    image: openinterpreter
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./files:/app/files
    environment:
      - OPENAI_API_KEY
    command: interpreter -y --custom_instructions "Be as concise as possible"
